all:
  vars:
    ansible_user: root
    ansible_become: yes

  children:
    brokers:
      hosts:
        kafka1:
          ansible_host: 172.16.16.151
          kafka_role: broker
          heap: 6G
          kafka_tarball: ./roles/common/files/kafka_2.13-3.7.2.tgz
          java_package: ./roles/common/files/openjdk-17.tar.gz
          install_dir: /opt/kafka
          ssl:
            enabled: true
            ca_cert: ./files/ca.crt
            ca_key: ./files/ca.key
            keystore_password: changeit
            truststore_password: changeit
          sasl:
            enabled: false
