all:
  vars:
    ansible_user: root
    ansible_become: yes

  children:
    brokers:
      hosts:
        kafka1:
          ansible_host: 172.16.16.177
          node_id: 1
          kafka_role: broker
          heap: 6G
          kafka_tarball: ./roles/common/files/kafka_2.13-3.7.2.tgz
          java_package: ./roles/common/files/openjdk-17.tar.gz
          install_dir: /opt/kafka
          ssl:
            enabled: true
            ca_cert: ./files/ca.crt
            ca_key: ./files/ca.key
            keystore_password: changeit
            truststore_password: changeit
          sasl:
            enabled: false

        kafka2:
          ansible_host: 172.16.16.185
          node_id: 2
          kafka_role: broker
          heap: 6G
          kafka_tarball: ./roles/common/files/kafka_2.13-3.7.2.tgz
          java_package: ./roles/common/files/openjdk-17.tar.gz
          install_dir: /opt/kafka
          ssl:
            enabled: true
            ca_cert: ./files/ca.crt
            ca_key: ./files/ca.key
            keystore_password: changeit
            truststore_password: changeit
          sasl:
            enabled: false

        kafka3:
          ansible_host: 172.16.16.189
          node_id: 3
          kafka_role: broker
          heap: 6G
          kafka_tarball: ./roles/common/files/kafka_2.13-3.7.2.tgz
          java_package: ./roles/common/files/openjdk-17.tar.gz
          install_dir: /opt/kafka
          ssl:
            enabled: true
            ca_cert: ./files/ca.crt
            ca_key: ./files/ca.key
            keystore_password: changeit
            truststore_password: changeit
          sasl:
            enabled: false

    connect:
      hosts:
        connect1:
          ansible_host: 172.16.16.190
          kafka_role: connect
          heap: 2G
          kafka_tarball: ./roles/common/files/kafka_2.13-3.7.2.tgz
          java_package: ./roles/common/files/openjdk-17.tar.gz
          install_dir: /opt/kafka
          connect_group_id: connect-cluster
          plugin_path: /opt/kafka/plugins
          use_ssl_bootstrap: true

#    mm2:
 #     hosts:
  #      mm2-1:
   #       ansible_host: 172.16.16.186
    #      kafka_role: mm2
     #     heap: 2G
      #    kafka_tarball: ./roles/common/files/kafka_2.13-3.7.2.tgz
       #   java_package: ./roles/common/files/openjdk-17.tar.gz
        #  install_dir: /opt/kafka
         # bootstrap_servers: "172.16.16.82:9092,172.16.16.168:9092,172.16.16.144:9092"
