all:
  vars:
    ssl_enabled: true
    kafka_version: 3.7.2
    java_version: 17
    base_dir: /opt/kafka
    logs_dir: /data/logs
    config_dir: /etc/kafka/configs
    ssl_dir: /etc/kafka/configs/secrets
    kafka_user: kafka
    kafka_group: kafka

  children:
    kafka_controllers:
      vars:
        data_dir: /data/kafkadata/controller
      hosts:
        node1:
          ansible_host: 172.16.16.140
        node2:
          ansible_host: 172.16.16.150
        node3:
          ansible_host: 172.16.16.170

    kafka_brokers:
      vars:
        data_dir: /data/kafkadata/broker
      hosts:
        node1:
          ansible_host: 172.16.16.140
        node2:
          ansible_host: 172.16.16.150
        node3:
          ansible_host: 172.16.16.170
 
    kafka_connect:
      vars:
        data_dir: /data/kafkadata/connect
      hosts:
        node4:   
          ansible_host: 172.16.16.167
