---
# ---------------- Java Section ----------------
- name: Ensure Java install directory exists
  file:
    path: "{{ install_dir }}/java"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Extract Java tarball
  unarchive:
    src: "{{ java_package }}"
    dest: "{{ install_dir }}/java"
    remote_src: no

- name: Detect JDK directory
  find:
    paths: "{{ install_dir }}/java"
    file_type: directory
    patterns: "jdk-*"
  register: jdk_dir

- name: Set JAVA_HOME fact
  set_fact:
    java_home: "{{ jdk_dir.files[0].path }}"

- name: Write JAVA_HOME and PATH to profile
  copy:
    dest: /etc/profile.d/java.sh
    mode: 0755
    content: |
      export JAVA_HOME={{ java_home }}
      export PATH=$JAVA_HOME/bin:$PATH

# ---------------- Kafka Section ----------------
- name: Create Kafka install dir
  file:
    path: "{{ install_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Extract Kafka tarball
  unarchive:
    src: "{{ kafka_tarball }}"
    dest: "{{ install_dir }}"
    remote_src: no
    extra_opts: [--strip-components=1]

# ---------------- Kafka Connect Configuration ----------------
- name: Configure Kafka Connect distributed.properties
  template:
    src: connect-distributed.properties.j2
    dest: "{{ install_dir }}/config/connect-distributed.properties"
    mode: 0644
  notify: restart kafka-connect

# ---------------- Kafka Connect systemd Service ----------------
- name: Configure Kafka Connect systemd service
  template:
    src: kafka-connect.service.j2
    dest: /etc/systemd/system/kafka-connect.service
    mode: 0644

- name: Reload systemd
  command: systemctl daemon-reload
  become: yes

- name: Enable and start Kafka Connect
  systemd:
    name: kafka-connect
    state: started
    enabled: yes
